version: "3.9"

services:
  web:
    build: .
    container_name: nouvel_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - db
      - redis

  worker:
    build: .
    container_name: nouvel_worker
    command: celery -A config.celery:app worker --loglevel=INFO
    env_file:
      - .env.docker
    depends_on:
      - web
      - redis
      - db

  beat:
    build: .
    container_name: nouvel_beat
    command: celery -A config.celery:app beat --loglevel=INFO
    env_file:
      - .env.docker
    depends_on:
      - worker
      - redis
      - db

  db:
    image: postgres:16
    container_name: nouvel_db
    environment:
      POSTGRES_DB: nouvel
      POSTGRES_USER: nouvel
      POSTGRES_PASSWORD: nouvel
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: nouvel_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
