# ---------------------------------------------------------------------
# Render Blueprint for Nouvel-EMR — Free plan
# Web + Postgres; Celery runs eagerly in-process.
# ---------------------------------------------------------------------

services:
  - type: web
    name: nouvel-emr
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      # Create superuser if missing (works with custom USERNAME_FIELD=email)
      python manage.py createsuperuser --noinput || true
      # Run deploy checks but DON'T fail the build on warnings
      python manage.py check --deploy
    startCommand: gunicorn config.wsgi:application --workers=${WEB_CONCURRENCY:-2} --bind 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: config.prod

      # Your settings read DJANGO_SECRET_KEY
      - key: DJANGO_SECRET_KEY
        generateValue: true

      - key: DJANGO_DEBUG
        value: False

      - key: DJANGO_ALLOWED_HOSTS
        value: nouvel-emr.onrender.com,.onrender.com
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: https://nouvel-emr.onrender.com,https://*.onrender.com

      - key: USE_X_FORWARDED_PROTO
        value: True
      - key: DJANGO_TIME_ZONE
        value: Europe/Paris
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: WEB_CONCURRENCY
        value: 2

      # Database connection
      - key: DATABASE_URL
        fromDatabase:
          name: nouvel-postgres
          property: connectionString

      # Celery eager (no worker on free plan)
      - key: CELERY_TASK_ALWAYS_EAGER
        value: True

      # Non-interactive superuser vars expected by Django
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin@nouvel-emr.com
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@nouvel-emr.com
      - key: DJANGO_SUPERUSER_PASSWORD
        generateValue: true

databases:
  - name: nouvel-postgres
    plan: free
