# Generated by Django 5.2.6 on 2025-10-30 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=140, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Service category",
                "verbose_name_plural": "Service categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="services", to="services.servicecategory"
            ),
        ),
    ]
