# Generated by Django 5.2.6 on 2025-10-24 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
        ("patients", "0003_patient_patients_pa_merged__567d2b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="patients.patient",
            ),
        ),
    ]
