# Generated by Django 5.2.6 on 2025-10-03 03:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_patient_patients_pa_merged__567d2b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Encounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="encounters",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-start"],
            },
        ),
        migrations.CreateModel(
            name="ClinicalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("S", "Subjective"),
                            ("O", "Objective"),
                            ("A", "Assessment"),
                            ("P", "Plan"),
                            ("N", "Note"),
                        ],
                        default="N",
                        max_length=1,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "encounter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="encounters.encounter",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("systolic", models.PositiveIntegerField(blank=True, null=True)),
                ("diastolic", models.PositiveIntegerField(blank=True, null=True)),
                ("heart_rate", models.PositiveIntegerField(blank=True, null=True)),
                ("resp_rate", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=4, null=True
                    ),
                ),
                ("spo2", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "encounter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vitals",
                        to="encounters.encounter",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["clinician", "start"], name="encounters__clinici_1343b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="encounter",
            index=models.Index(
                fields=["patient", "start"], name="encounters__patient_060735_idx"
            ),
        ),
    ]
