# Generated by Django 5.2.6 on 2025-10-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_patient_patients_pa_merged__567d2b_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("loinc_code", models.CharField(blank=True, default="", max_length=64)),
                ("is_panel", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("priority", models.CharField(default="routine", max_length=16)),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ordered", "Ordered"),
                            ("collected", "Collected"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="ordered",
                        max_length=16,
                    ),
                ),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="labs.labcatalog",
                    ),
                ),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiagnosticReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("status", models.CharField(default="final", max_length=16)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "performing_lab",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "pdf",
                    models.FileField(blank=True, null=True, upload_to="lab_reports/"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="patients.patient",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="labs.laborder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, default="", max_length=64)),
                ("name", models.CharField(max_length=255)),
                ("value_num", models.FloatField(blank=True, null=True)),
                (
                    "value_text",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                ("ref_low", models.FloatField(blank=True, null=True)),
                ("ref_high", models.FloatField(blank=True, null=True)),
                ("flag", models.CharField(blank=True, default="", max_length=16)),
                ("note", models.CharField(blank=True, default="", max_length=255)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observations",
                        to="labs.diagnosticreport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specimen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("identifier", models.CharField(blank=True, default="", max_length=64)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specimen",
                        to="labs.laborder",
                    ),
                ),
            ],
        ),
    ]
