# Generated by Django 5.2.6 on 2025-10-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laborder",
            name="priority",
            field=models.CharField(
                choices=[
                    ("routine", "Routine"),
                    ("urgent", "Urgent"),
                    ("stat", "STAT"),
                ],
                default="routine",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="laborder",
            name="status",
            field=models.CharField(
                choices=[
                    ("ordered", "Ordered"),
                    ("in_progress", "In progress"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="ordered",
                max_length=20,
            ),
        ),
    ]
