# Generated by Django 5.2.6 on 2025-10-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0002_alter_laborder_priority_alter_laborder_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diagnosticreport",
            name="status",
            field=models.CharField(
                choices=[
                    ("final", "Final"),
                    ("partial", "Partial"),
                    ("corrected", "Corrected"),
                ],
                default="final",
                max_length=16,
            ),
        ),
    ]
