# Generated by Django 5.2.6 on 2025-10-16 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labs", "0004_externallabresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="externallabresult",
            name="is_deleted_by_patient",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="externallabresult",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="externallabresult",
            name="vendor_name",
            field=models.CharField(
                blank=True, help_text="Lab/facility name", max_length=200
            ),
        ),
    ]
