# Generated by Django 5.2.6 on 2025-09-15 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("given_name", models.CharField(max_length=100)),
                ("family_name", models.CharField(max_length=100)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("sex", models.CharField(blank=True, default="", max_length=20)),
                ("phone", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "external_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "address_line",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("city", models.CharField(blank=True, default="", max_length=100)),
                ("region", models.CharField(blank=True, default="", max_length=100)),
                (
                    "postal_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["family_name", "given_name", "id"],
                "indexes": [
                    models.Index(
                        fields=["family_name", "given_name"],
                        name="patients_pa_family__a96a9c_idx",
                    ),
                    models.Index(
                        fields=["date_of_birth"], name="patients_pa_date_of_4302f5_idx"
                    ),
                    models.Index(fields=["email"], name="patients_pa_email_bb026d_idx"),
                    models.Index(fields=["phone"], name="patients_pa_phone_fc49bb_idx"),
                    models.Index(
                        fields=["external_id"], name="patients_pa_externa_261412_idx"
                    ),
                ],
            },
        ),
    ]
