# Generated by Django 5.2.6 on 2025-09-18 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_patient_is_active_patient_merged_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="patient",
            index=models.Index(
                fields=["merged_into"], name="patients_pa_merged__567d2b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="patient",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("merged_into__isnull", True),
                    models.Q(("pk", models.F("merged_into")), _negated=True),
                    _connector="OR",
                ),
                name="patient_not_merged_into_self",
            ),
        ),
    ]
