# Generated by Django 5.2.6 on 2025-09-17 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0002_patient_is_active_patient_merged_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=255)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "clinician",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-start", "id"],
                "indexes": [
                    models.Index(fields=["start"], name="appointment_start_3ae143_idx"),
                    models.Index(fields=["end"], name="appointment_end_04837b_idx"),
                    models.Index(
                        fields=["status"], name="appointment_status_8fe9d7_idx"
                    ),
                    models.Index(
                        fields=["clinician", "start"],
                        name="appointment_clinici_00b373_idx",
                    ),
                    models.Index(
                        fields=["patient", "start"],
                        name="appointment_patient_de3304_idx",
                    ),
                ],
            },
        ),
    ]
