# Generated by Django 5.2.6 on 2025-09-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0003_availability_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="reminder_24h_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_2h_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
