# Generated by Django 5.2.6 on 2025-10-27 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable key, e.g. 'main', 'footer'.", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Menu",
                "verbose_name_plural": "Menus",
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="Optional icon class/name", max_length=120
                    ),
                ),
                (
                    "url_kind",
                    models.CharField(
                        choices=[
                            ("reverse", "Internal (named URL)"),
                            ("path", "Internal (raw path)"),
                            ("external", "External URL"),
                            ("none", "No link (header/label)"),
                        ],
                        default="reverse",
                        max_length=10,
                    ),
                ),
                (
                    "named_url",
                    models.CharField(
                        blank=True,
                        help_text="Django named URL (e.g. 'services:detail')",
                        max_length=200,
                    ),
                ),
                (
                    "url_kwargs",
                    models.JSONField(
                        blank=True, help_text="Dict of kwargs for reverse()", null=True
                    ),
                ),
                (
                    "url_query",
                    models.JSONField(
                        blank=True, help_text="Optional query dict to append", null=True
                    ),
                ),
                ("internal_path", models.CharField(blank=True, max_length=300)),
                ("external_url", models.URLField(blank=True)),
                ("open_in_new_tab", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("auth", "Authenticated users"),
                            ("staff", "Staff only"),
                            ("super", "Superusers only"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                (
                    "is_mega",
                    models.BooleanField(
                        default=False,
                        help_text="If true, children render in a wide grid panel on hover (top-level only).",
                    ),
                ),
                (
                    "mega_columns",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Number of grid columns for the mega panel (2–6).",
                        validators=[
                            django.core.validators.MinValueValidator(2),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="menus.menu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="menus.menuitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Menu item",
                "verbose_name_plural": "Menu items",
                "ordering": ["menu", "parent__id", "order", "id"],
            },
        ),
    ]
